/**
 * InsightsPanel.jsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Plain-English findings generated by compareRunner's verdict.
 */

import { motion } from 'framer-motion'
import { CheckCircle2, AlertTriangle, XCircle, Lightbulb } from 'lucide-react'
import { ALGO_BY_ID } from '../../constants.js'
import styles from './InsightsPanel.module.css'

const KIND = {
  success: { icon: CheckCircle2, className: styles.success, label: 'Good' },
  warning: { icon: AlertTriangle, className: styles.warning, label: 'Caution' },
  danger:  { icon: XCircle, className: styles.danger, label: 'Problem' },
  info:    { icon: Lightbulb, className: styles.info, label: 'Note' },
}

export default function InsightsPanel({ comparison }) {
  const { insights } = comparison.verdict

  return (
    <ul className={styles.list}>
      {insights.map((item, i) => {
        const { icon: Icon, className, label } = KIND[item.kind] ?? KIND.info
        const algo = item.algoId ? ALGO_BY_ID[item.algoId] : null
        return (
          <motion.li
            key={i}
            className={`${styles.item} ${className}`}
            initial={{ opacity: 0, x: -8 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.05 }}
          >
            <span className={styles.icon} aria-label={label}><Icon size={16} /></span>
            <p className={styles.text}>{item.text}</p>
            {algo && (
              <span className={styles.tag} style={{ '--c': algo.color }}>{algo.shortName}</span>
            )}
          </motion.li>
        )
      })}
    </ul>
  )
}
